### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ggh505** [csfoo/contrafold-se#1]
Hi, I keep getting the following error when running make in my contrafold-se/src directory.

make: *** [Makefile:49: Contrafold.o] Error 1

I do not have this error when on my mac, but when trying to compile on my Ubuntu desktop I have issues...

Thanks!
Grace

**Comment by csfoo** [comment]
Hi, not sure if you still have this issue but can you paste the full set of compilation outputs involving gcc? This isn't enough information to help you debug.

**Comment by xanthexu** [comment]
I have the same problem. Does any one know what is going on ?

**Comment by csfoo** [comment]
@xanthexu please try again as I have merged a patch
